export const gothSentences = [
  "We are all broken, that's how the light gets in.",
  "In the darkness, I find my true self.",
  "JSON, like my soul, is best formatted in black.",
  "Embrace the error, for it is part of the void.",
  "Even the prettiest code has a shadow.",
  "Let the night guide your indentation.",
  "Goth girls do it with style... and valid JSON.",
  "Every bracket closed is a secret kept.",
  "Beauty in the dark, order in the chaos.",
  "My heart beats in hexadecimal.",
  "The prettifier whispers secrets to the night.",
  "Malformed JSON is a curse upon this realm.",
  "Tabs or spaces? Only the abyss knows.",
  "Let your code be as enigmatic as the moon.",
  "In the silence of the night, errors echo loudest.",
  "A single comma can shatter the illusion.",
  "The void stares back when your JSON is invalid.",
  "Let your code bleed elegance and darkness.",
  "Indentation is the poetry of structure.",
  "In the crypt of code, only the valid survive.",
  "Let the shadows format your thoughts.",
  "A goth heart beats in curly braces.",
  "The night is long, but the code is eternal.",
  "Let your syntax be as sharp as your eyeliner.",
  "In the realm of JSON, only the brave persist."
];